'use client'

import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import {
  LayoutDashboard,
    FolderKanban,
      Users,
        FileText,
          Receipt,
            MessageSquare,
              Settings,
                Zap,
                  ChevronRight,
                    TrendingUp,
                      LogOut,
                      } from 'lucide-react'
                      import { createBrowserClient } from '@supabase/ssr'
                      
                      const NAV = [
                        { href: '/dashboard', icon: LayoutDashboard, label: 'Dashboard' },
                          { href: '/projects', icon: FolderKanban, label: 'Projects' },
                            { href: '/crew', icon: Users, label: 'Freelancers' },
                              { href: '/contracts', icon: FileText, label: 'Contracts' },
                                { href: '/invoices', icon: Receipt, label: 'Invoices' },
                                  { href: '/messages', icon: MessageSquare, label: 'Messages' },
                                  ]
                                  
                                  function getDaysLeft(trialEndsAt: string | null): number | null {
                                    if (!trialEndsAt) return null
                                      const diff = new Date(trialEndsAt).getTime() - Date.now()
                                        return Math.max(0, Math.ceil(diff / (1000 * 60 * 60 * 24)))
                                        }
                                        
                                        export default function Sidebar() {
                                          const pathname = usePathname()
                                            const router = useRouter()
                                              const [workspaceName, setWorkspaceName] = useState('My Workspace')
                                                const [trialDays, setTrialDays] = useState<number | null>(null)
                                                  const [subscriptionStatus, setSubscriptionStatus] = useState<string>('trialing')
                                                    const [initial, setInitial] = useState('W')
                                                    
                                                      useEffect(() => {
                                                          const supabase = createBrowserClient(
                                                                process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                                                      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
                                                                          )
                                                                          
                                                                              async function load() {
                                                                                    const { data: { user } } = await supabase.auth.getUser()
                                                                                          if (!user) return
                                                                                          
                                                                                                const { data: profile } = await supabase
                                                                                                        .from('profiles')
                                                                                                                .select('workspace_name, trial_ends_at, subscription_status, full_name')
                                                                                                                        .eq('id', user.id)
                                                                                                                                .single()
                                                                                                                                
                                                                                                                                      if (profile) {
                                                                                                                                              const name = profile.workspace_name || profile.full_name || 'My Workspace'
                                                                                                                                                      setWorkspaceName(name)
                                                                                                                                                              setInitial(name.charAt(0).toUpperCase())
                                                                                                                                                                      setSubscriptionStatus(profile.subscription_status || 'trialing')
                                                                                                                                                                              setTrialDays(getDaysLeft(profile.trial_ends_at))
                                                                                                                                                                                    }
                                                                                                                                                                                        }
                                                                                                                                                                                        
                                                                                                                                                                                            load()
                                                                                                                                                                                              }, [])
                                                                                                                                                                                              
                                                                                                                                                                                                async function handleLogout() {
                                                                                                                                                                                                    const supabase = createBrowserClient(
                                                                                                                                                                                                          process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                                                                                                                                                                                                process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
                                                                                                                                                                                                                    )
                                                                                                                                                                                                                        await supabase.auth.signOut()
                                                                                                                                                                                                                            router.push('/login')
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                const statusLabel =
                                                                                                                                                                                                                                    subscriptionStatus === 'active'
                                                                                                                                                                                                                                          ? 'Active'
                                                                                                                                                                                                                                                : subscriptionStatus === 'trialing'
                                                                                                                                                                                                                                                      ? trialDays !== null
                                                                                                                                                                                                                                                              ? `Trial · ${trialDays} day${trialDays !== 1 ? 's' : ''} left`
                                                                                                                                                                                                                                                                      : 'Trial'
                                                                                                                                                                                                                                                                            : subscriptionStatus === 'past_due'
                                                                                                                                                                                                                                                                                  ? 'Past due'
                                                                                                                                                                                                                                                                                        : 'Inactive'
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                              <div className="flex flex-col h-screen w-64 bg-[#060C18] border-r border-[#1A2540] fixed left-0 top-0 z-40">
                                                                                                                                                                                                                                                                                                    <div className="px-5 py-5 border-b border-[#1A2540]">
                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                      <div className="w-8 h-8 rounded-xl bg-amber-400 flex items-center justify-center shadow-lg shadow-amber-400/20">
                                                                                                                                                                                                                                                                                                                                  <Zap className="w-4 h-4 text-black fill-black" />
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                  <span className="text-white font-bold text-lg tracking-tight">CrewDesk</span>
                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-1 mt-0.5">
                                                                                                                                                                                                                                                                                                                                                                                            <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-[10px] text-slate-500 font-medium">All systems live</span>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mx-4 mt-3 mb-2 px-3 py-3 rounded-xl bg-[#0A1020] border border-[#1A2540]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-amber-400 to-amber-600 flex items-center justify-center text-xs font-bold text-black">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {initial}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex-1 min-w-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs font-semibold text-white truncate">{workspaceName}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[10px] text-slate-500">{statusLabel}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ChevronRight className="w-3.5 h-3.5 text-slate-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="px-5 pt-4 pb-1 text-[10px] font-semibold text-slate-600 uppercase tracking-widest">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Navigation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <nav className="flex-1 px-3 space-y-0.5 overflow-y-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {NAV.map(item => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const isActive = pathname === item.href || pathname.startsWith(item.href + '/')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const Icon = item.icon
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link key={item.href} href={item.href}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`flex items-center gap-3 px-3 py-2.5 rounded-xl transition-all cursor-pointer relative hover:translate-x-0.5 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isActive
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? 'bg-amber-400/10 text-amber-400'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : 'text-slate-400 hover:text-white hover:bg-white/5'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {isActive && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="absolute left-0 top-1/2 -translate-y-1/2 w-0.5 h-5 bg-amber-400 rounded-full -ml-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Icon className={`w-4 h-4 flex-shrink-0 ${isActive ? 'text-amber-400' : ''}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className={`text-sm flex-1 ${isActive ? 'font-semibold' : 'font-medium'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="px-3 pb-4 space-y-1 border-t border-[#1A2540] pt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link href="/settings">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={`flex items-center gap-3 px-3 py-2.5 rounded-xl transition-all cursor-pointer ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pathname === '/settings'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? 'bg-amber-400/10 text-amber-400'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : 'text-slate-400 hover:text-white hover:bg-white/5'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Settings className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-sm font-medium">Settings</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {subscriptionStatus !== 'active' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/pricing">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center gap-2 px-3 py-2.5 rounded-xl bg-amber-400/5 border border-amber-400/10 hover:bg-amber-400/10 transition-colors cursor-pointer mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <TrendingUp className="w-3.5 h-3.5 text-amber-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-xs font-semibold text-amber-400">Upgrade Plan</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-all cursor-pointer mt-1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <LogOut className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-sm font-medium">Sign out</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }'